repositories {
    mavenLocal()
    flatDir {
        dir "libs"
    }
    mavenCentral()

    exclusiveContent { // Modrinth Maven
        forRepository { maven { url = "https://api.modrinth.com/maven/" } }
        filter { includeGroup("maven.modrinth") }
    }
    exclusiveContent { // Curseforge Maven
        forRepository { maven { url = "https://cursemaven.com/" } }
        filter { includeGroup("curse.maven") }
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
}