plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    alias libs.plugins.modDevGradleLegacy
    alias libs.plugins.spotless
    alias libs.plugins.kotlin.jvm
    alias libs.plugins.kotlin.plugin
}

version = mod_version

// Mojang从1.20.5开始向最终用户提供Java 21，因此mod应面向Java 21。
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

// 包含数据生成器生成的资源.
sourceSets.main.resources { srcDir 'src/generated/resources' }

apply from: "$projectDir/gradle/scripts/moddevgradle.gradle"
apply from: "$projectDir/dependencies.gradle"
apply from: "$projectDir/gradle/scripts/resources.gradle"
apply from: "$projectDir/gradle/scripts/jars.gradle"
apply from: "$projectDir/gradle/scripts/repositories.gradle"
apply from: "$projectDir/gradle/scripts/spotless.gradle"

generateModMetadata.doFirst {
    mkdir('run/client')
    mkdir('run/server')
    mkdir('run/data')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs << "-Xlint:-deprecation" << "-Xlint:-removal"
}

jar{
    exclude "**/.cache"
    exclude "**/SimplifiedToTraditional.properties"
}

java {
    withSourcesJar()
}

version = mod_version
group = mod_group_id

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

// IDEA不再自动下载依赖项的源码/javadoc jar，因此需要显式启用此行为。
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}